### PR TITLE
Fix QtWebKitWidgets import

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
Thanks!

**Comment by lucarebuffi** [comment]
Thank you! I will be completing the refactoring of XRayServer asap. For sure, I will try to do it before my visit to Argonne in December.

**Comment by lucarebuffi** [comment]
Dear Tom, I fully restored the functionalities of XRayServer widgets. Please refer to version 1.0.19

**Comment by tschoonj** [comment]
Hi Luca,

Thanks for updating the package. However I cannot update the package with pip as it keeps saying that 1.0.18 is the latest version for OASYS1-XrayServer. Strangely on PyPy it says that 1.0.19 is the latest though...

Any clues on how to fix this?

**Comment by lucarebuffi** [comment]
This is normal with Pypi, the misalignment can take more than two days. I got used to that.
You can download the .tar.gz file of 1.0.19 version and install it manually:

pip install OASYS1-XRayServer-1.0.19.tar.gz --upgrade

**Comment by lucarebuffi** [comment]
Anyway, it seems available now.

**Comment by lucarebuffi** [comment]
The version is correct, but the package you download is still the 1.0.18, without any modification. I definitely hate Pypi right now.

**Comment by tschoonj** [comment]
Ok, I will wait until tomorrow then before trying again

**Comment by lucarebuffi** [comment]
yep, I checked the .tar.gz and it is the correct one, but Pypi is doing messy.

**Pull request merged**
